### ISSUE TITLE
phpoffice/phpexcel zamjena sa phpoffice/phpspreadsheet

### ISSUE THREAD

**Issue by gokkstudio** [kowach/evidencija-radnog-vremena#1]
Hej man, super ti je projekt, ima li nade da zamjeniš phpoffice/phpexcel sa phpoffice/phpspreadsheet?

**Comment by kowach** [comment]
Tko bi rekao da netko koristi ovaj moj projekt :smiley: 
Još sam prošle godine prebacio na phpoffice ali sam zaboravio pushati na github.
A druga stvar je što sam promijenio sada kalendar tako da ne uzima sve one čudne praznike od googlea.

**Comment by gokkstudio** [comment]
:) indeed. Naletio sam na tvoj projekt dok sam tražio za osobnu uporabu nekakvo riješenje i nemožeš vjerovat - there is none! Ovo tvoje je odlično i radi kako spada.
Samo mi je kvaka kako da prekovremene sate dodjelim (npr ako imam random viška sati na random dane)?

Sve ostalo super stvar, hvala ti na nadopuni kalendara!

**Comment by kowach** [comment]
Da, bilo kakve random stvari se dodaju naknadno, kad se izgenerira excel file.
Ideja mi je jednog dana napraviti full aplikaciju, ovo je bilo sklepano samo da mi ubrza neke procese u firmi.
